### ISSUE TITLE
Failed to find module: "nativescript-periscopehearts/periscopehearts.android", relative to: app/tns_modules/

### ISSUE THREAD

**Issue by ishandutta2007** [bradmartin/nativescript-periscopehearts#2]
Trying to implement in angular, let me know if I am doing anything wrong, nativescript-periscopehearts doesn't seem to get copied over to app/tns_modules/

app.component.ts

`elementRegistryModule.registerElement("PeriscopeHearts", () => require("nativescript-periscopehearts/periscopehearts.android").PeriscopeHearts);
`

testing.component.ts
```
import { Page } from 'ui/page';
import { PeriscopeHearts} from 'nativescript-periscopehearts/periscopehearts.android';

@Component({
  moduleId: module.id,
  selector: 'bb-testing',
  templateUrl: 'testing.html',
  styleUrls: ['testing.css'],
})
export class TestingComponent {
  private _heartLayout : PeriscopeHearts;
   constructor(
    private page: Page,
   ) {
    this._heartLayout = <PeriscopeHearts>page.getViewById("heartLayout");
   }

  newHeart() {
    var colorArray = [
      { hex: "#3489db" },
      { hex: '#FF4081' },
      { hex: '#229911' },
      { hex: '#fff000' }
    ];
    var rand = colorArray[Math.floor(Math.random() * colorArray.length)];
    this._heartLayout.addHeart(rand.hex);
  }
}
```

testing.html

```
<StackLayout>
  <Button text="Add Heart" (tap)="newHeart()"></Button>
   <PeriscopeHearts class="heartLayout" id="heartLayout" height="400">
   </PeriscopeHearts>
</StackLayout>
```

I get the following error on loading the page.

> ERROR Error: Uncaught (in promise): TypeError: Could not load view for: PeriscopeHearts.Error: com.tns.NativeScriptException: Failed to find module: "nativescript-periscopehearts/periscopehearts.android", relative to: app/tns_modules/

**Comment by jlooper** [comment]
It seems as if you have a build error here, such that the app isn't finding the plugin files where it's expecting to. Brad has written an article on this: https://bradmartin.net/2016/07/20/ahhh-this-nativescript-plugin-doesnt-work/

One thing I'd try is to make sure you can run the demo app. Does it work?

**Comment by jlooper** [comment]
In addition, this plugin is not updated to 3.x. It would only work if you are on 2.5 (unless someone wants to PR some updates here)

**Comment by ishandutta2007** [comment]
Actually the demo doesn't build either, I followed  https://bradmartin.net/2016/07/20/ahhh-this-nativescript-plugin-doesnt-work/ steps in both the cases,  here is the error for demo **on 2.5.2**

> No manifest found in /Users/ishandutta2007/Documents/Projects/nativescript-periscopehearts/demo/app/App_Resources/Android/AndroidManifest.xml
> 
> Error: sed: no such file or directory: /Users/ishandutta2007/Documents/Projects/nativescript-periscopehearts/demo/app/App_Resources/Android/app.gradle.
> Check if you're using an outdated template and update it.
> Project successfully created.
> Preparing project...
> No manifest found in /Users/ishandutta2007/Documents/Projects/nativescript-periscopehearts/demo/app/App_Resources/Android/AndroidManifest.xml
> No manifest found in /Users/ishandutta2007/Documents/Projects/nativescript-periscopehearts/demo/app/App_Resources/Android/AndroidManifest.xml
> 
> :dexNativescriptperiscopeheartsTns-core-modules-widgetsDebug FAILED

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':dexNativescriptperiscopeheartsTns-core-modules-widgetsDebug'.
> > com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED
> 

I tried with 3.x as well as 2.5.2, in 3.x I don't seem to get AndroidManifest missing error but only the other error (ie when tns-core-modules is set to "latest")

**Comment by bradmartin** [comment]
Demo now works with 2.5, the app template needed to be updated.

As for your code, I think you might have the wrong require call on `registerElement()` try dropping the trailing `periscope.android` from the module path. Just use the module name `"nativescript-periscopehearts"` for the require.

**Comment by ishandutta2007** [comment]
Well for me the demo build succeeds but still crashes on device with following exception

> 
> An uncaught Exception occurred on "main" thread.
> java.lang.RuntimeException: Unable to start activity ComponentInfo{org.rachid.khayyat/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Failed to find module: "nativescript-periscopehearts", relative to: app/tns_modules/
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2308)
> 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2368)
> 	at android.app.ActivityThread.access$800(ActivityThread.java:144)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1285)
> 	at android.os.Handler.dispatchMessage(Handler.java:102)
> 	at android.os.Looper.loop(Looper.java:135)
> 	at android.app.ActivityThread.main(ActivityThread.java:5235)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at java.lang.reflect.Method.invoke(Method.java:372)
> 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
> Caused by: com.tns.NativeScriptException: Failed to find module: "nativescript-periscopehearts", relative to: app/tns_modules/
> 	at com.tns.Module.resolvePathHelper(Module.java:159)
> 	at com.tns.Module.resolvePath(Module.java:60)
> 	at com.tns.Runtime.callJSMethodNative(Native Method)
> 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
> 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
> 	at com.tns.Runtime.callJSMethod(Runtime.java:1047)
> 	at com.tns.Runtime.callJSMethod(Runtime.java:1028)
> 	at com.tns.Runtime.callJSMethod(Runtime.java:1018)
> 	at com.tns.NativeScriptActivity.onCreate(android.app.Activity.java)
> 	at android.app.Activity.performCreate(Activity.java:6001)
> 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2261)
> 	... 10 more

**Comment by bradmartin** [comment]
Can you explain the steps you're taking to run the demo?

**Comment by ishandutta2007** [comment]
```
git clone https://github.com/bradmartin/nativescript-periscopehearts.git
cd nativescript-periscopehearts/demo
tns plugin add nativescript-periscopehearts
tns build android
tns run android
```

**Comment by ishandutta2007** [comment]
Deleted the repo and also tried the following from scratch, same results

```
git clone https://github.com/bradmartin/nativescript-periscopehearts.git
cd nativescript-periscopehearts/demo
tns run android
```

**Comment by ishandutta2007** [comment]
logcat:
> I/art (23737): Late-enabling -Xcheck:jni I/TNS.Native(23737): NativeScript Runtime Version 2.5.0, commit 95dd12d69eba88755158987d8c4666a9c5aa5e07 D/TNS.Native(23737): JNI_ONLoad D/TNS.Native(23737): JNI_ONLoad END D/TNS.Native(23737): Failed to load snapshot: dlopen failed: library "libsnapshot.so" not found D/TNS.Native(23737): V8 version 5.5.372.32 D/TNS.Native(23737): lenNodes=66804, lenNames=775867, lenValues=880208 D/TNS.Native(23737): time=5 D/TNS.Java(23737): Enabling NativeScript Debugger Agent E/art (23737): invalid stream - problem with parameter iterator in /data/app/org.rachid.khayyat-1/base.apk for method void com.tns.NativeScriptActivity.onCreate(android.os.Bundle) D/AndroidRuntime(23737): Shutting down VM W/System.err(23737): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.rachid.khayyat/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Failed to find module: "nativescript-periscopehearts", relative to: app/tns_modules/ W/System.err(23737): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2308) W/System.err(23737): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2368) W/System.err(23737): 	at android.app.ActivityThread.access$800(ActivityThread.java:144) W/System.err(23737): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1285) W/System.err(23737): 	at android.os.Handler.dispatchMessage(Handler.java:1

**Comment by bradmartin** [comment]
Try not running `tns plugin add` the build step will look for it locally.
Just clone, run `tsc` cd demo, tns platform add android, tns run
android and it should work. Sorry that's not outlined perfectly well or
simpler with a script in the package.json. Did this plugin long ago :)

**Comment by ishandutta2007** [comment]
`tsc` cd demo ?

**Comment by bradmartin** [comment]
You'll have to transpile the ts files prior to pathing into the demo.
Sorry. On my phone.

**Comment by bradmartin** [comment]
On comp now:

```
git clone ...
cd to the project /// so cd nativescript-periscopehearts
tsc
cd demo
tns platform add android
tns run android
```

**Comment by ishandutta2007** [comment]
```
git clone https://github.com/bradmartin/nativescript-periscopehearts.git
cd nativescript-periscopehearts
tsc
```

> error TS2318: Cannot find global type 'Array'.
> error TS2318: Cannot find global type 'Boolean'.
> error TS2318: Cannot find global type 'Function'.
> error TS2318: Cannot find global type 'IArguments'.
> error TS2318: Cannot find global type 'Number'.
> error TS2318: Cannot find global type 'Object'.
> error TS2318: Cannot find global type 'RegExp'.
> error TS2318: Cannot find global type 'String'.
> error TS6053: File '/Users/ishandutta2007/Documents/Projects/nativescript-periscopehearts/demo/node_modules/tns-core-modules/tns-core-modules.d.ts' not found.
> error TS6053: File '/Users/ishandutta2007/Documents/Projects/nativescript-periscopehearts/manual_typings/base.d.ts' not found.
> error TS6053: File '/Users/ishandutta2007/Documents/Projects/nativescript-periscopehearts/node_modules/tns-platform-declarations/tns-core-modules/android17.d.ts' not found.
> error TS6053: File '/Users/ishandutta2007/Documents/Projects/nativescript-periscopehearts/node_modules/tns-platform-declarations/tns-core-modules/ios/ios.d.ts' not found.
> error TS6053: File '/Users/ishandutta2007/Documents/Projects/nativescript-periscopehearts/node_modules/tns-platform-declarations/tns-core-modules/org.nativescript.widgets.d.ts' not found.
> error TS6053: File '/Users/ishandutta2007/Documents/Projects/nativescript-periscopehearts/node_modules/typescript/lib/lib.core.d.ts' not found.

**Comment by ishandutta2007** [comment]
Despite the above transpiling errors
```
git clone https://github.com/bradmartin/nativescript-periscopehearts.git
cd nativescript-periscopehearts
tsc
cd demo
tns platform add android
tns run android
```
installs the app and let me manually launch it without any crash or error. 💯

**Comment by bradmartin** [comment]
Did you try changing your registerElement call in your angular app and
seeing if that fixed it?

**Comment by ishandutta2007** [comment]
Yes that part got sorted, it's no more crashing but now I am facing a different issue, it seems I am not accessing the page elements the right way,

``` <PeriscopeHearts class="heartLayout" id="heartLayout" height="400"></PeriscopeHearts>```
```
alert('page: ' + page);//Page(2)
alert('heartLayout: ' + <PeriscopeHearts>page.getViewById("heartLayout"));//undefined.
```
I was trying to reproduce [2975](https://github.com/NativeScript/NativeScript/issues/2975) removing the cardview.
But for me anything within page is undefined
```
   var topmost = frameModule.topmost();
   alert('topmost: ' + topmost);//Frame(1);
   alert('currentPage: ' + topmost.currentPage);//Page(2)
   alert('currentPage._isAddedToNativeVisualTree: '  + topmost.currentPage._isAddedToNativeVisualTree);//true
   alert('injected page: ' + page);//Page(748)
   alert('X: ' + page.getViewById('emailContainer'));//undefined
   alert('Y: ' + page.getViewById('loginBtn'));//undefined
   alert('Z: ' + page.getViewById('emailTextField'));//undefined
   alert('cp:X: ' + topmost.currentPage.getViewById('emailContainer'));//undefined
   alert('cp:Y: ' + topmost.currentPage.getViewById('loginBtn'));//undefined
   alert('cp:Z: ' + topmost.currentPage.getViewById('emailTextField'));//undefined
```
modified html is like this
``` 
<GridLayout id="emailContainer" class="m-t-5 m-b-5" rows="auto, auto" columns="40, *">
  <Label row="0" col="0" text="&#xE0BE;" class="material-icon center font-18" textWrap="true" >
  </Label>
  <TextField id="emailTextField" class="input-field" row="0" col="1" text="Yoo" hint="Email..." editable="true" keyboardType="email" returnKeyType="next" >
  </TextField>
  <Label text="Noo" row="1" col="1" textWrap="true" >
  </Label>
</GridLayout>
<Button id="loginBtn" text="LogIn" class="btn-block btn-light-blue" >
</Button>
```

**Comment by bradmartin** [comment]
Aren't you using angular? If so try setting your id's the angular way with `#loginBtn` syntax and not the property `id`. Hope that helps. As for this plugin I think all the issues are cleared up now 😄 if anything specific with this plugin just let me know.

**Comment by ishandutta2007** [comment]
Actually after changing it to angular way it fails inside the library, inside the prototype method in tns_modules, `this._android` is undefined I guess, maybe you would like to have a look.

Somewhere here: https://github.com/bradmartin/nativescript-periscopehearts/blob/0c9acb1b3a15d139ecd30f9bcb9e1371ae660198/periscopehearts.android.ts#L18

The error:
> TypeError: Cannot read property 'addHeart' of undefined
> File: "file:///data/data/org.nativescript.bbnsng210June/files/app/tns_modules/@angular/core/bundles/core.umd.js, line: 13024, column: 8
> 
> StackTrace: 
> 	Frame: function:'PeriscopeHearts.addHeart', file:'file:///data/data/org.nativescript.bbnsng210June/files/app/tns_modules/nativescript-periscopehearts/periscopehearts.js', line: 19, column: 22
> 	Frame: function:'WebRtcViewComponent.newHeart', file:'file:///data/data/org.nativescript.bbnsng210June/files/app/modules/webrtcview/webrtcview.component.js', line: 39, column: 24
> 	Frame: function:'', file:'', line: 81, column: 24
> 	Frame: function:'handleEvent', file:'file:///data/data/org.nativescript.bbnsng210June/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 11805, column: 138

The calling code is this:
```
  @ViewChild('heartLayout') heartLayout_el: ElementRef;
  ngAfterViewInit(): void {
    this.peri_heart_el_native = <PeriscopeHearts>(this.heartLayout_el.nativeElement);
    alert('this.peri_heart_el_native:' + this.peri_heart_el_native);//PeriscopeHearts(771)
  }
  newHeart() {
    let colorArray = [{ hex: "#3489db" }, { hex: '#FF4081' }, { hex: '#229911' }, { hex: '#fff000' }];
    let rand = colorArray[Math.floor(Math.random() * colorArray.length)];
    this.peri_heart_el_native.addHeart(rand.hex);
  }
```
and the template:
```
<side-drawer-page>
  <StackLayout class="coverImage">
    <Button text="Add Heart" (tap)="newHeart()"></Button>
    <PeriscopeHearts #heartLayout class="heartLayout" height="400">
    </PeriscopeHearts>
  </StackLayout>
</side-drawer-page>
```
